/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uas.pbo;

import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.*;
import javax.swing.event.*;
import javax.swing.*;

/**
 *
 * @author ashadipermana
 */
public class PanelItem extends javax.swing.JPanel {

    /**
     * Creates new form PanelItem
     */
    private ImageIcon originalIcon;

    public PanelItem() {
        initComponents();
        lblgambar.addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                // Memastikan updateImage dipanggil ketika komponen siap ditampilkan
                updateImage();
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblgambar = new javax.swing.JLabel();
        btnbeli = new javax.swing.JButton();
        lblnama = new javax.swing.JLabel();
        lblkategori = new javax.swing.JLabel();
        lbljenis = new javax.swing.JLabel();
        txtdeskripsi = new javax.swing.JTextField();
        lbljumlah = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btnbeli.setText("BELI");
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });

        lblnama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnama.setText("jLabel2");

        lblkategori.setText("Kategori");

        lbljenis.setText("jenis");

        txtdeskripsi.setEditable(false);
        txtdeskripsi.setText("deskripsi");
        txtdeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeskripsiActionPerformed(evt);
            }
        });

        lbljumlah.setText("Jumlah");

        lblharga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblharga.setForeground(new java.awt.Color(255, 51, 51));
        lblharga.setText("Harga");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PCS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblnama)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblkategori)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbljenis))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbljumlah)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel1)
                                    .addGap(99, 99, 99)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblharga)
                                .addGap(62, 62, 62)
                                .addComponent(btnbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtdeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnama)
                    .addComponent(lblkategori)
                    .addComponent(lbljenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljumlah)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblharga))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeskripsiActionPerformed

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed
          // Mendapatkan detail item
        String namaBarang = lblnama.getText();
        int hargaBarang = Integer.parseInt(lblharga.getText());
        int jumlahBarang = Integer.parseInt(lbljumlah.getText());

        // Mendapatkan saldo user
        HomeForm homeForm = (HomeForm) SwingUtilities.getWindowAncestor(this);
        String fullname = homeForm.getFullname();
        int saldoUser = homeForm.getSaldo(fullname);

        // Menampilkan konfirmasi pembelian
        int response = JOptionPane.showConfirmDialog(this, "Ingin membeli " + namaBarang + " dengan harga Rp" + hargaBarang + "?", "Konfirmasi Pembelian", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            if (saldoUser >= hargaBarang && jumlahBarang > 0) {
                // Mengurangi saldo user
                int newSaldo = saldoUser - hargaBarang;
                homeForm.updateSaldo(fullname, newSaldo);

                // Mengurangi jumlah barang
                int newJumlahBarang = jumlahBarang - 1;
                lbljumlah.setText(String.valueOf(newJumlahBarang));

                // Menambah riwayat transaksi
                homeForm.addTransaksi(fullname, namaBarang, hargaBarang);
                homeForm.updateSaldoLabel(fullname);

                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Pembelian berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Saldo tidak mencukupi atau barang habis.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnbeliActionPerformed

    public void setLblNama(String nama) {
        lblnama.setText(nama);
    }

    public void setLblKategori(String kategori) {
        lblkategori.setText(kategori);
    }

    public void setLblJenis(String jenis) {
        lbljenis.setText(jenis);
    }

    public void setTxtDeskripsi(String deskripsi) {
        txtdeskripsi.setText(deskripsi);
    }

    public void setLblJumlah(String jumlah) {
        lbljumlah.setText(jumlah);
    }

    public void setLblHarga(String harga) {
        lblharga.setText(harga);
    }

    public void setLblGambar(ImageIcon icon) {
        this.originalIcon = icon;
        updateImage();
    }

    public void updateImage() {
        // Memastikan ukuran label diperbarui
        lblgambar.revalidate();

        int labelWidth = lblgambar.getWidth();
        int labelHeight = lblgambar.getHeight();

        if (labelWidth > 0 && labelHeight > 0 && originalIcon != null) {
            // Mengubah ukuran gambar sesuai dengan ukuran label
            Image scaledImage = originalIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

            // Mengkonversi Image ke ImageIcon agar bisa ditampilkan di JLabel
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            lblgambar.setIcon(scaledIcon);
        } else if (originalIcon != null) {
            // Jika ukuran label belum siap, gunakan ukuran default dari originalIcon
            lblgambar.setIcon(originalIcon);

            // Menggunakan SwingUtilities.invokeLater untuk menunda eksekusi hingga ukuran label siap
            SwingUtilities.invokeLater(this::updateImage);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblgambar;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lbljenis;
    private javax.swing.JLabel lbljumlah;
    private javax.swing.JLabel lblkategori;
    private javax.swing.JLabel lblnama;
    private javax.swing.JTextField txtdeskripsi;
    // End of variables declaration//GEN-END:variables
}
