/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uas.pbo;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author ashadipermana
 */
public class PanelTransaksi extends javax.swing.JPanel {

    private DefaultListModel<String> listModel;
    private DbKoneksi dbKoneksi;

    public PanelTransaksi() {
        initComponents();
        dbKoneksi = new DbKoneksi();
        listModel = new DefaultListModel<>();
        listViewTransaksi.setModel(listModel);
        loadTransaksi();
    }

    public void loadTransaksi() {
        listModel.clear();
        try (Connection conn = dbKoneksi.getConnection()) {
            String query = "SELECT username, nama_gambar, harga, status FROM transaksi";
            try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

                while (rs.next()) {
                    String username = rs.getString("username");
                    String namaBarang = rs.getString("nama_gambar");
                    int harga = rs.getInt("harga");
                    String status = rs.getString("status");
                    String transaksiInfo = "Username: " + username + ", Nama Barang: " + namaBarang + ", Harga: " + harga + ", Status: " + status;
                    listModel.addElement(transaksiInfo);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listViewTransaksi = new javax.swing.JList<>();

        listViewTransaksi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listViewTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listViewTransaksi;
    // End of variables declaration//GEN-END:variables
}
